### ISSUE TITLE
same class

### ISSUE THREAD

**Issue by maxlibin** [kenken17/kCSS#2]
https://github.com/kenken17/kCSS/blob/9856b88190a98d9f2872b916cc287daf4f0d3ad5/scss/base/_breakpoints.scss#L6

.child.mobile-is-1,
.mobile-is-1.container, 
.child.m-is-1,
.m-is-1.container {
...

.child.mobile-is-1 and .child.m-is-1 is same, I suggest choose one name and reduce the code base.

**Comment by kenken17** [comment]
Ya this is by purpose. Because when u have more classes in the markup, you will see this come in handy. lol `mobile` is more readable, but `m` will be for more regular user.

**Comment by maxlibin** [comment]
https://github.com/kenken17/kCSS/commit/85dc526c8823192cd3bb62df9dabe9d0d65aa038
